"""create wish model

Revision ID: 8fb1d169cb15
Revises: c0db5a502012
Create Date: 2026-04-27 23:42:40.332557

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fb1d169cb15"
down_revision: Union[str, Sequence[str], None] = "c0db5a502012"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wish",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reserved_by_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.String(length=255), nullable=False),
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ARCHIVED", "ACTIVE", "RESERVED", "DONE", name="wishstatus"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("PERSONAL", "FRIENDS_ONLY", "PUBLIC", name="wishtype"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum("LOW", "MODERATE", "HIGH", name="wishcategory"),
            nullable=False,
        ),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reserved_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wish")
    # ### end Alembic commands ###
