"""remove redundant reserved status

Revision ID: 971e442a2a4c
Revises: e56f6a5433f6
Create Date: 2026-05-15 11:52:27.684201

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "971e442a2a4c"
down_revision: Union[str, Sequence[str], None] = "e56f6a5433f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
