"""add events model

Revision ID: d7010362269d
Revises: 32bc4d4bc4c9
Create Date: 2026-05-20 11:52:23.796400

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d7010362269d"
down_revision: Union[str, Sequence[str], None] = "32bc4d4bc4c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
