"""add unique constraint to friends

Revision ID: c0db5a502012
Revises: 2491595ffc02
Create Date: 2026-04-26 22:18:39.967810

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c0db5a502012"
down_revision: Union[str, Sequence[str], None] = "2491595ffc02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "friends", ["person_id", "friend_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "friends", type_="unique")
    # ### end Alembic commands ###
