"""make pfp nullable

Revision ID: 562afe6e141e
Revises: ab866bccc738
Create Date: 2026-05-03 20:10:27.187591

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "562afe6e141e"
down_revision: Union[str, Sequence[str], None] = "ab866bccc738"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "pfp", existing_type=sa.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "pfp", existing_type=sa.VARCHAR(length=255), nullable=False)
    # ### end Alembic commands ###
