"""add unique constraint for title and user_id

Revision ID: 32bc4d4bc4c9
Revises: 971e442a2a4c
Create Date: 2026-05-19 15:44:06.202967

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32bc4d4bc4c9"
down_revision: Union[str, Sequence[str], None] = "971e442a2a4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("wish_title_key"), "wish", type_="unique")
    op.create_unique_constraint(None, "wish", ["title", "user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "wish", type_="unique")
    op.create_unique_constraint(
        op.f("wish_title_key"), "wish", ["title"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
