"""remove name default

Revision ID: f60b2d83a14f
Revises: 562afe6e141e
Create Date: 2026-05-03 20:11:21.672896

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f60b2d83a14f"
down_revision: Union[str, Sequence[str], None] = "562afe6e141e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
