"""fix_timestamp_timezone_default

Revision ID: 8330bb78aad5
Revises: 5a93d06a35e7
Create Date: 2026-04-20 22:39:19.633623

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8330bb78aad5"
down_revision: Union[str, Sequence[str], None] = "5a93d06a35e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
