"""move from nullables to type hints

Revision ID: e56f6a5433f6
Revises: f60b2d83a14f
Create Date: 2026-05-10 14:47:59.467145

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e56f6a5433f6"
down_revision: Union[str, Sequence[str], None] = "f60b2d83a14f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("wish", "body", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("wish", "link", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "wish", "image_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "wish", "image_url", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "wish", "link", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "wish", "body", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
