"""add properties to User model

Revision ID: ab866bccc738
Revises: 0c5a2066fdd8
Create Date: 2026-05-03 20:04:27.615120

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab866bccc738"
down_revision: Union[str, Sequence[str], None] = "0c5a2066fdd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(length=100), nullable=False))
    op.add_column("user", sa.Column("is_staff", sa.Boolean(), nullable=False))
    op.add_column("user", sa.Column("pfp", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "pfp")
    op.drop_column("user", "is_staff")
    op.drop_column("user", "name")
    # ### end Alembic commands ###
